### ISSUE TITLE
Support all countries

### ISSUE THREAD

**Issue by licaon-kter** [TheKyleJohnson90/XMPPJabberClient#1]
Does it? Or mainly the USA?

**Comment by TheKyleJohnson90** [comment]
This supports multiple languages. Please feel free to add your own if it is not already implemented.

**Comment by licaon-kter** [comment]
This was not about the language...but I forgot exactly.

Anyway, what's the status of this fork?

**Comment by TheKyleJohnson90** [comment]
This fork is no longer maintained regularly.  Please use https://github.com/iNPUTmice/Conversations
