### ISSUE TITLE
Some code missing in repo 

### ISSUE THREAD

**Issue by umerk44** [TheKyleJohnson90/XMPPJabberClient#3]
I can't find the PushManagementService and EmojiService in the code. Please check if it's missed in the commit.

**Comment by TheKyleJohnson90** [comment]
This fork project is not being heavily supported or developed further. Please use the original source https://github.com/inputmice/Conversations

**Comment by licaon-kter** [comment]
@TheKyleJohnson90 can you take it down from Play then? People would erroneusly install it...
